csvfiles_index:
    path:     /
    defaults: { _controller: "AppBundle:CsvFiles:index" }
    methods:  GET

csvfiles_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:CsvFiles:show" }
    methods:  GET

csvfiles_new:
    path:     /new
    defaults: { _controller: "AppBundle:CsvFiles:new" }
    methods:  [GET, POST]

csvfiles_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:CsvFiles:edit" }
    methods:  [GET, POST]

csvfiles_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:CsvFiles:delete" }
    methods:  DELETE
