featurename_index:
    path:     /
    defaults: { _controller: "AppBundle:FeatureName:index" }
    methods:  GET

featurename_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:FeatureName:show" }
    methods:  GET

featurename_new:
    path:     /new
    defaults: { _controller: "AppBundle:FeatureName:new" }
    methods:  [GET, POST]

featurename_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:FeatureName:edit" }
    methods:  [GET, POST]

featurename_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:FeatureName:delete" }
    methods:  DELETE
