partner_index:
    path:     /
    defaults: { _controller: "AppBundle:Partner:index" }
    methods:  GET

partner_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Partner:show" }
    methods:  GET

partner_new:
    path:     /new
    defaults: { _controller: "AppBundle:Partner:new" }
    methods:  [GET, POST]

partner_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Partner:edit" }
    methods:  [GET, POST]

partner_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Partner:delete" }
    methods:  DELETE
