paymenttype_index:
    path: /
    defaults: { _controller: "AppBundle:PaymentType:index" }
    methods: GET

paymenttype_show:
    path: /{id}/show
    defaults: { _controller: "AppBundle:PaymentType:show" }
    methods: GET

paymenttype_new:
    path: /new
    defaults: { _controller: "AppBundle:PaymentType:new" }
    methods: [GET, POST]

paymenttype_edit:
    path: /{id}/edit
    defaults: { _controller: "AppBundle:PaymentType:edit" }
    methods: [GET, POST]

paymenttype_delete:
    path: /{id}/delete
    defaults: { _controller: "AppBundle:PaymentType:delete" }
    methods: DELETE