unitmeasure_index:
    path:     /
    defaults: { _controller: "AppBundle:UnitMeasure:index" }
    methods:  GET

unitmeasure_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:UnitMeasure:show" }
    methods:  GET

unitmeasure_new:
    path:     /new
    defaults: { _controller: "AppBundle:UnitMeasure:new" }
    methods:  [GET, POST]

unitmeasure_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:UnitMeasure:edit" }
    methods:  [GET, POST]

unitmeasure_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:UnitMeasure:delete" }
    methods:  DELETE
